# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

# MAGIC %sql
# MAGIC USE CATALOG `hashchuk_pn`;
# MAGIC USE SCHEMA `self_picked_assigment`;

# COMMAND ----------

import matplotlib.pyplot as plt
import pandas as pd

# Load Gold table
df = spark.table("hashchuk_pn.self_picked_assigment.artists_by_location").toPandas()

# Sort for readability
df_sorted = df.sort_values("unique_artists", ascending=False).head(20)

plt.figure(figsize=(12, 6))
plt.barh(df_sorted["artist_location"], df_sorted["unique_artists"])
plt.xlabel("Unique Artists")
plt.ylabel("Location")
plt.title("Top Artist Locations (GOLD Table)")
plt.gca().invert_yaxis()  # bigger on top
plt.show()


# COMMAND ----------

df = spark.table("hashchuk_pn.self_picked_assigment.longest_songs").toPandas()


# Sort and select top 20 already done
df_top20 = df.sort_values("duration_minutes", ascending=False)

# Create the bar plot
plt.figure(figsize=(12, 6))
plt.barh(
    df_top20["song_title"][::-1],  # reverse to have longest on top
    df_top20["duration_minutes"][::-1],
    color='skyblue'
)

plt.xlabel("Duration (minutes)")
plt.title("Top Longest Songs")
plt.tight_layout()
plt.show()



# COMMAND ----------

import pandas as pd
import matplotlib.pyplot as plt

# Load the table from Spark
df = spark.table("hashchuk_pn.self_picked_assigment.songs_by_year").toPandas()

# Sort by year
df_sorted = df.sort_values("year")

# Plot
plt.figure(figsize=(14, 6))
plt.bar(df_sorted["year"], df_sorted["total_songs"], color='teal')

plt.xlabel("Year")
plt.ylabel("Total Songs")
plt.title("Number of Songs by Year")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

